export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENT = "INIT_INGREDIENT";
export const INIT_INGREDIENT_FAILED = "INIT_INGREDIENT_FAILED";

export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_FAIL = "PURCHASE_ORDER_FAIL";
export const PURCHASE_ORDER_START = "PURCHASE_ORDER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

